### ISSUE TITLE
Bug: jaeger-client 4.1.0 cannot send udp packet when using gevent with monkey.patch_all()

### ISSUE THREAD

**Issue by floatliang** [jaegertracing/jaeger-client-python#256]
## Problem -jaeger-client 4.1.0 cannot send udp packet when using gevent with monkey.patch_all()

hi all, when i using jaeger-client 4.1.0, tornado 5.1.1 with gevent and monkey patch. jaeger-agent cannot receive udp from client， my code is like this:
```python
import gevent
from gevent import monkey
monkey.patch_all()
import random
from flask import Flask, Response
import requests
from flask_tracer import FlaskTracer

tracer = FlaskTracer(config={
    'sampler': {
        'type': 'const',
        'param': 1,
    },
    'local_agent': {
        'reporting_host': '',
        'reporting_port': '',
        'sampling_port': ''
    },
    'logging': True
}, service_name='gateway', validate=True, is_async=True)

app = Flask(__name__)

@app.route('/')
@tracer.trace_inbound_request()
def handle():
    url = 'http://localhost:25003/token/{}/'.format(token)
    with tracer.trace_outbound_request(headers=headers, rpc_name='token'):
        requests.get(url, headers=headers)
    url = 'http://localhost:25001/assets/{}/'.format(1)
    with tracer.trace_outbound_request(headers=headers, rpc_name='assets'):
        requests.get(url, headers=headers)

app.run(port=28081)
```
and i got a trace graph like this：
![image](https://user-images.githubusercontent.com/33773361/64102505-b7967e00-cda2-11e9-8462-315ad6880cdb.png)
![image](https://user-images.githubusercontent.com/33773361/64102565-d3018900-cda2-11e9-96b1-96cb6951d9e7.png)

it lost spans of the 'gateway' service (the service above).

BUT when i using jaeger-client 4.0.0 , tornado 4.6.3 with gevent and monkey patch, it works fine:

![image](https://user-images.githubusercontent.com/33773361/64102801-44d9d280-cda3-11e9-9bd5-3711cf3c38d3.png)
![image](https://user-images.githubusercontent.com/33773361/64102843-58853900-cda3-11e9-8505-5f05414b3cbb.png)

I guess maybe there is some problem with tornado 5.1.1 and gevent.monkey.patch_all()

Best regards!

**Comment by yurishkuro** [comment]
Are you saying that it worked with earlier version of Jaeger?

**Comment by floatliang** [comment]
Yes,it works fine with jaeger-client 4.0.0.
But when i switch it to jaeger-client 4.1.0, it will lost spans. 
I noticed that 4.0.0 using tornado 4.6.3 while 4.1.0 using tornado 5.1.1.
So i guess tornado maybe the root cause of this problem.

**Comment by yurishkuro** [comment]
cc @condorcet any ideas about this?

**Comment by condorcet** [comment]
@floatliang Which version of python are you using?

**Comment by floatliang** [comment]
@condorcet python 3.7.1

**Comment by condorcet** [comment]
There are some difference between management and API of Tornado event loop and asyncio loop. The last one using as default event loop in Tornado 5+ on Python 3.
Actually `threadloop` is not ready for higher versions of Tornado. My assumption:  `gevent.monkey.patch_all()` patches threading module that way that function in another one thread will be executed actually in the same thread. In the same time `threadloop` creates event loop in new thread unconditionally. But there are already another one and asyncio breaks down with error `RuntimeError: Cannot run the event loop while another loop is running`

@floatliang  I made quick-fix of `threadloop` in my fork https://github.com/condorcet/threadloop/commit/236c342dc8594c8d73849c670cd57946f2549451 Could you please try it in your project?

**Comment by floatliang** [comment]
@condorcet  thanks for your help!  i'll try it later, if this fix helps i'll let you know.

**Comment by floatliang** [comment]
@condorcet  I still cannot get any spans from 'gateway' service:
![image](https://user-images.githubusercontent.com/33773361/64225367-b6ce2b00-cf0d-11e9-9149-4edab1e6c9b2.png)
![image](https://user-images.githubusercontent.com/33773361/64225377-bcc40c00-cf0d-11e9-8fe5-7e19deb6ee34.png)


Here is my pip packages in virtualenv:
![image](https://user-images.githubusercontent.com/33773361/64225306-6fe03580-cf0d-11e9-92af-81cb60dc3bd7.png)

I install your threadloop package using:
```shell
pip install git+https://github.com/condorcet/thretornado-5-supporting
```

Am i made any mistake?

**Comment by condorcet** [comment]
@floatliang Thank you! My apologize, I think it's my mistake and I made wrong commit :) Please try again, I've updated the branch with another one dirty-fix.

**Comment by floatliang** [comment]
@condorcet  hi， still not work.
I use pdb.set_trace() in _start_io_loop(self) and found that：
![image](https://user-images.githubusercontent.com/33773361/64240958-6d91d180-cf35-11e9-8517-31b749bdf6de.png)

It seems there is no current loop in new thread , so it didn't enter `if _io_loop`.

**Comment by condorcet** [comment]
@floatliang Ok, it means there are another problem. Is it possible to share your project or made an example? I'll try to find the problem.

**Comment by floatliang** [comment]
@condorcet  hi , i upload this demo to my github repository: 
https://github.com/floatliang/jaeger_tracing_example

I deploy all components in docker and in the same machine.

**Comment by condorcet** [comment]
@floatliang Thank you.
@yurishkuro Patching standard library with `gevent` makes multi-threaded code single-threaded. And it seems that `_consume_queue` fall into lock here https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/reporter.py#L161
I think it's better to report span always via `add_callback` https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/reporter.py#L132 
```
def report_span(self, span):
        self.io_loop.add_callback(self._report_span_from_ioloop, span)
```
I made this fix locally and it helps to avoid lock. I got spans in jaeger.

**Comment by yurishkuro** [comment]
@condorcet agreed. Do you want to make a PR?

**Comment by yurishkuro** [comment]
NB: it was unnecessary optimization while trying to fix the bug where we were putting into queue directly from `report_span`, which didn't work from another thread.

**Comment by condorcet** [comment]
@yurishkuro Ok, I'll make PR. But my first assumption still valid. If someone want to use `gevent.monkey.patch` with asyncio applications (e.g. based on Tornado 5+), they can face with that problem :) I don't think that we should solving it, just keep in mind.

**Comment by Jamim** [comment]
> I don't think that we should solving it, just keep in mind.

I believe it's worth mentioning in the documentation (in case it's not mentioned yet).
